import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mechanical Guidance Disclaimer",
  description:
    "Important disclaimer regarding AI-generated mechanical guidance in VictoryRevConnect Boaters.",
};

export default function DisclaimerPage() {
  return (
    <section className="bg-white py-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Warning banner */}
        <div className="bg-amber-50 border-l-4 border-amber-500 rounded-r-xl p-5 mb-10">
          <p className="text-amber-800 font-semibold text-sm">
            IMPORTANT: This page must be reviewed by a licensed attorney before the App is distributed to end users. The content below is a placeholder template and does not constitute legal advice.
          </p>
        </div>

        <h1 className="text-4xl font-extrabold text-[#0A2240] mb-2">
          Mechanical Guidance Disclaimer
        </h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: June 2026</p>

        <div className="text-gray-700 leading-relaxed space-y-8">

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">For Informational Purposes Only</h2>
            <p>
              The AI mechanic agent in VictoryRevConnect Boaters (&ldquo;the Agent&rdquo;) provides guidance that is sourced from publicly available manufacturer documentation, support knowledge bases, and parts catalog data. All guidance generated by the Agent is provided <strong>for informational and reference purposes only.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">Not a Substitute for Professional Advice</h2>
            <p>
              The Agent is <strong>not a certified marine mechanic</strong> and its guidance does not constitute professional mechanical advice. You should always consult with a qualified, licensed marine mechanic before performing any repairs on your vessel — particularly for:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2 text-gray-600">
              <li>Fuel systems and fuel delivery components</li>
              <li>Electrical systems, wiring, and battery systems</li>
              <li>Steering and drive systems</li>
              <li>Hull integrity and structural repairs</li>
              <li>Any repair that could affect passenger safety</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">Accuracy Limitations</h2>
            <p>
              While the Agent draws from approved manufacturer sources, it may produce inaccurate, incomplete, or outdated information. Manufacturer specifications change across model years. Always verify guidance against your specific boat&apos;s model year documentation before proceeding.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">Emergency Procedures</h2>
            <p>
              In any genuine onboard emergency — fire, flooding, medical emergency, or loss of control — <strong>call for help immediately.</strong> In the United States, contact the US Coast Guard on VHF Channel 16 or call 911. Pre-loaded emergency guidance in the App is provided as a supplement to, not a replacement for, proper safety training and emergency protocols.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">No Warranty</h2>
            <p>
              The mechanical guidance provided by the Agent is offered &ldquo;as is&rdquo; without warranty of any kind, express or implied, including but not limited to warranties of accuracy, completeness, fitness for a particular purpose, or non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, VictoryRevConnect Boaters, its officers, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2 text-gray-600">
              <li>Reliance on or use of AI-generated mechanical guidance</li>
              <li>Any repair, modification, or maintenance performed based on guidance from the Agent</li>
              <li>Any personal injury, property damage, or loss resulting from the above</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">User Responsibility</h2>
            <p>
              By using the AI mechanic agent, you acknowledge that you have read, understood, and agreed to this disclaimer. You accept sole responsibility for any decisions made based on Agent guidance and for verifying such guidance with a qualified professional before acting on it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0A2240] mb-3">Contact</h2>
            <p>
              Questions about this disclaimer:{" "}
              <a href="mailto:hello@victoryrevconnect.com" className="text-[#C8102E] hover:underline">
                hello@victoryrevconnect.com
              </a>
            </p>
          </section>

          {/* Attorney review callout */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mt-10">
            <h3 className="font-bold text-amber-900 mb-2">⚠️ Attorney Review Required Before Launch</h3>
            <p className="text-amber-800 text-sm leading-relaxed">
              This disclaimer is a template and has not been reviewed by a licensed attorney. Per the pre-launch checklist in the blueprint, attorney review of the mechanical guidance disclaimer must be completed before the first EAS build is distributed to real devices. Do not distribute this content to users without legal review.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
